name: "Garry’s Data Visualization & Analytics Portfolio"
title: "Garry Grimes | Data Visualization & Analytics"
description: "Banking + MIS + FinTech → Dashboards & Analysis in Power BI and Excel"
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
logo: /PowerPoint/exports/cover_slide.png   # cleaner to serve from repo
show_downloads: false
