name: "Garry’s Data Visualization & Analytics Portfolio"
title: "Garry Grimes | Data Visualization & Analytics"
description: "Banking + MIS + FinTech → Dashboards & analysis in Power BI and Excel"

url: "https://ggrimes620.github.io"
baseurl: "/PowerBI-Excel-Portfolio"

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

logo: "{{ site.baseurl }}/PowerPoint/exports/cover_slide.png"
show_downloads: false
