# _config.yml
name: "Garry’s Data Viz & Analytics Portfolio"
description: "Banking + MIS + FinTech → Data storytelling with Power BI, Excel, and PowerPoint"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
logo: https://cvws.icloud-content.com/B/AaY5TVysb1xyFFXlPENrMa4_e2htAeYYxT3RwxJllpFPRHtzLrq5wkSC/GarryG.jpeg?o=Av3mspqj3QGdGAfpxY49RPg2dgn1ouzScAzKsWWBPQ2_&v=1&x=3&a=CAogfRQfpm8WcjTXYIsm8GGBrKoz1dCXY-H5K8y4_aRGL0cSbxDJ_aKelDMYydr-n5QzIgEAUgQ_e2htWgS5wkSCaid0DfV5tzS10S6Vpi9kbD4vhY7jlC4tVHMc1BomclgOirqEgwqSA3dyJ7XA3RxPWVqfbuG5zNIQn3lzk7vojnezoIu-AQtuOc0V8L7WSm92wQ&e=1757782453&fl=&r=62e710e1-ae2c-4c28-8002-52cc2e9a883c-1&k=QTwMzCKcLCAROQkvmhl7Fg&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=182&s=WrQt74Yg863IMnxcosmmhBYWmn0&cd=i
show_downloads: false
