# _config.yml
name: "Garry’s Data Viz & Analytics Portfolio"
description: "Banking + MIS + FinTech → Data storytelling with Power BI, Excel, and PowerPoint"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
logo: https://cvws.icloud-content.com/B/AXdDe42voXV9W_AbxzlHn4s5osPeAWkan5BgxO3zxq50frbptLOumJ9W/GarryG.jpeg?o=AqDnenFfyWxgEuKaIPF2filbUdC03t2kB6gCo4PzGIw1&v=1&x=3&a=CAogOZhykThlV9w5jpi5ffLBx74f8QDIzS_cbfiVb_6E5R0SbxCJt5melDMYiZT1n5QzIgEAUgQ5osPeWgSumJ9WaifvAUsnYirsMod8yU7lcsOBTkG_FRsZlYsyrGsewIo3fTpb2Q5c1d9yJx0AjW8Y5XYeGuRpDUEpXRyPUpWLeWoxqG6uBgibeBrZKF0-Trp0lA&e=1757782297&fl=&r=a500e9c2-a748-46d5-a06f-a813b0096196-1&k=NB7_vM2PbwQ3_OS0Zqwsag&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=182&s=mJuAVliLG-775UI3TFF8NqAYDdk&cd=i
show_downloads: false
