name: "Garry’s Data Visualization & Analytics Portfolio"
title: "Garry Grimes | Data Visualization & Analytics"
description: "Banking + MIS + FinTech → Dashboards & analysis in Power BI and Excel"

remote_theme: pages-themes/cayman@v0.2.0
logo: {{ site.baseurl }}/PowerPoint/exports/cover_slide.png

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: "https://ggrimes620.github.io"
baseurl: "/PowerBI-Excel-Portfolio"

show_downloads: false
